theme: jekyll-theme-cayman

title: Netflix Genre List
description: All the Netflix genres
show_downloads: false

collections:
  genres:
    output: true

defaults:
  -
    scope:
      path: ""
      type: genres
    values:
      layout: list

ignore:
  README.md

permalink: pretty

liquid:
  error_mode: strict
